apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  # The tip o' the iceberg
  # https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-api-elasticsearch-k8s-elastic-co-v1.html
  version: 7.17.5
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false